"""edited Plant model

Revision ID: 2a4344ca7b0e
Revises: 85ff3d8ff85f
Create Date: 2021-12-13 15:05:04.994534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4344ca7b0e'
down_revision = '85ff3d8ff85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('plant_type', sa.String(length=100), nullable=True),
    sa.Column('light', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('water', sa.String(length=100), nullable=True),
    sa.Column('fertilizer', sa.String(length=100), nullable=True),
    sa.Column('humidity', sa.String(length=100), nullable=True),
    sa.Column('pests', sa.String(length=100), nullable=True),
    sa.Column('fun_fact', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    # ### end Alembic commands ###
